security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        from_database:
            entity:
                class: App\Entity\User
                property: username 

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            lazy: true
            logout:
                 path: /logout
                 target: /
          
                        

            # authentification via HTTP Vasic
            # http_basic: true

            # authentification via form, check_path pour modifier le chemin par defaut check_path en login
            form_login: 
                check_path: login

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
 
    encoders:
        # A mettre avec http_basic
        # Symfony\Component\Security\Core\User\User: plaintext

        # Pour un bon encodage du password, le cost peut être supp à 12
        App\Entity\User:
            algorithm: bcrypt
            cost: 12

